using System;
using System.Collections.Generic;
using System.Text;

namespace RPG_Battle
{
    class Player
    {
        public int hp;
        public string name;
        public int attack;
        public int defense;
        public int agility;
        Random random = new Random();

        public void setup(string name, int attack, int defense, int agility)
        {
            this.name = name;
            this.attack = attack;
            this.defense = defense;
            this.agility = agility;
            hp = 2;
        }
        public void display()
        {
            Console.WriteLine(" Name is " + name);
            Console.WriteLine("- current hp: " + hp);
            Console.WriteLine("- attack is: " + attack + " Defense is: " + defense + " and agility is: " + agility );
        }

        //randomly generate how much the player attacked based on their starting attack stat
        public int getAttackDamage()
        {
            int damage = random.Next(attack-3, attack+3);
            return damage;
        }
        public void getHit(int damage)
        {
            int damageTaken;
            damageTaken = damage - random.Next(defense - 3, defense + 3);
            if (damageTaken < 0)
            {
                damageTaken = 0;
            }
            hp = hp - damageTaken;
            if (hp <0)
            {
                hp = 0;
            }
            Console.WriteLine( name + " has taken " + damageTaken + " damage.");

        }

        //randomly generate how much the player defended based on their starting defense stat
        public int getDefense()
        {
            int defendedDamage = random.Next(defense-3, defense);
            return defendedDamage;
        }
        //take the amount defended and add to health
        public void doTheDefend(int defendedDamage)
        {
            int damageReduced = defendedDamage;
            if (damageReduced <0)
            {
                damageReduced = 0;
            }
            Console.WriteLine( name + " defended for " + damageReduced);
            hp = hp + damageReduced;
            if (hp >100)
            {
                hp = 100;
            }
        }

        //take the attack and defense generated by the players and apply the difference to hp
        public void defendAgainstAttack(int defendedDamage, int attackDamage)
        {
            Console.WriteLine(name + " will defend!");
            if (defendedDamage >= attackDamage)
            {
                hp = hp + attackDamage;
            }
            else if (defendedDamage < attackDamage)
            {
                hp = hp - (attackDamage - defendedDamage);
                if (hp < 0)
                {
                    hp = 0;
                }
            }
            else
            {
                hp = hp;
            }
        }
        public string getName()
        {
            Console.Write(name);
            return name;
        }
        public bool checkIfDead()
        {
            if (hp == 0)
            {
                Console.WriteLine("\n");
                Console.WriteLine(name + " has died.");
                Console.WriteLine("\n");
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Game Over");
                return true;
            }
            else
            {
                return false;
            }
        }
        public bool didPlayerDodge(int agility)
        {
            int chance = random.Next(100);
            if (chance <= 5)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        
    }
}
